### ISSUE TITLE
Issue with missing js

### ISSUE THREAD

**Issue by rubenaros** [atompie/tracardi#3]
Hello, 

I built the app with docker-compose up, and I had the following problems:

The path the app uses to invoke the .js is /app/static/js, but that directory does not exist. There is app/frontend/static/js.

I copied the information to /app/static/js/ and now it looks for the main.bd9b1100.chunk.js file and can't find it.

Can you help me?
Thank you very much

**Comment by atompie** [comment]
HI you were right I missed some files. Please

`git pull`

if you pulled form master. If not clone from master again and 

`docker-compose build`

and then 

`docker-compose up`
