### ISSUE TITLE
New Feature: Plugin to parse URL parameters

### ISSUE THREAD

**Issue by atompie** [atompie/tracardi#33]
Plugin that reads URI form context, parses it and returns as dict in payload.  This ire pretty easy task. Al you need is to get familiar with tracardi plugins.

**Comment by atompie** [comment]
@emge1 Hi are you doing this task? We would like to finish it before the end of this month, if you don't have time for them, let me know I will take care of it.

**Comment by emge1** [comment]
@atompie Hi. Yes, I'm doing. Yes, I know. Thank you. I think that I wrote the plugin properly but I didn't test it in Tracardi.
