### ISSUE TITLE
Connector for mongodb

### ISSUE THREAD

**Issue by atompie** [atompie/tracardi#35]
Plug-in that connects to mongodb and reads data based on provided query

**Comment by nero2310** [comment]
Query will use Mongodb query format ?
Do we will need projection ?

**Comment by atompie** [comment]
I think will use regular mongodb query format. And projection is a must. Some records can be huge. 

So query like: 

`{ qty: { $gt: 4 } }`

And projection. if you understand projection as:

Image result for what is mongodb projection
In MongoDB, projection means selecting only the necessary data rather than selecting whole of the data of a document.
