### ISSUE TITLE
Plugin: Language detection

### ISSUE THREAD

**Issue by atompie** [atompie/tracardi#74]
This is a simple plugin that calls https://api.meaningcloud.com/lang-4.0/identification
 and returns result.

# Requirements

MeaningCloud Free Account - it generates access-key
Use of aiohttp for all API calls

# Documentation

Documentation uses requests library but this plugin needs aiohttp instead.

https://learn.meaningcloud.com/developer/language-identification/4.0/doc/what-is-language-identification

# Example of aiohttp use in other plugins.

https://github.com/atompie/tracardi-zapier-webhook/blob/master/tracardi_zapier_webhook/plugin.py

**Comment by patromi** [comment]
.

**Comment by atompie** [comment]
Done in 0.6.0
