### ISSUE TITLE
Plugin: Integrate MeaningCloud Sentiment Analysis

### ISSUE THREAD

**Issue by atompie** [atompie/tracardi#75]
# Integrate MeaningCloud Sentiment Analysis

This is a simple plugin that calls 'https://api.meaningcloud.com/sentiment-2.1' and returns result.

# Requirements

MeaningCloud Free Account - it generates access-key
Use of aiohttp for all API calls

# Documentation

Documentation uses requests library but this plugin needs aiohttp instead. 

https://learn.meaningcloud.com/developer/sentiment-analysis/2.1/doc/request
https://learn.meaningcloud.com/developer/sentiment-analysis/2.1/dev-tools

Example of aiohttp use in other plugins.

https://github.com/atompie/tracardi-zapier-webhook/blob/master/tracardi_zapier_webhook/plugin.py

# Example call

curl 'https://api.meaningcloud.com/sentiment-2.1' \
    -F 'key=TOKEN-HERE' \
    -F 'txt=this is awsome' \
    -F 'lang=en'

**Comment by Arnab1181412** [comment]
can I work on this issue?

**Comment by atompie** [comment]
done in 0.6.0
