### ISSUE TITLE
Elasticsearch index prefix

### ISSUE THREAD

**Issue by stefaanneyts** [atompie/tracardi#76]
Hi

Use case: more than one Tracardi installation connected to only one Elasticsearch cluster

To make this scenario possible, it would be useful to have a setting to prefix the indices created by Tracardi.

Kind regards

Stefaan Neyts
___technical lead back-end
**duo.**
[www.duo.be](https://www.duo.be)

**Comment by atompie** [comment]
use env variable INSTANCE_PREFIX to define prefix on version 0.6.0

* `INSTANCE_PREFIX` - defines prefix for all elastic indexes. This can be used to run multiple instances of Tracardi on one elastic instance.
