### ISSUE TITLE
Events dint load after connecting to unomi

### ISSUE THREAD

**Issue by lokeshgrootan** [atompie/tracardi#9]
**Describe the bug**
After pulling latest tag and docker-compose up, tracardi couldnt load the events immediately, i see events after long time. but we could see events are triggered to elastic search

**Comment by atompie** [comment]
@lokeshgrootan Hi This can be a problem with your time zone. What time zone are you in? Could you give it a test and set a wide time range and see what the difference of the actual time the event was triggered and the time you see it in Tracardi. 

We have been working on timezone issue recently but t can still exist.

**Comment by lokeshgrootan** [comment]
Yes I suspect so, I am in IST Timezone (India). I have workaround with setting the time to my local time and then I could see details.

Thanks,
Lokesh

From: atompie ***@***.***>
Reply to: atompie/tracardi ***@***.***>
Date: Thursday, 13 May 2021 at 1:58 PM
To: atompie/tracardi ***@***.***>
Cc: Lokesh ***@***.***>, Mention ***@***.***>
Subject: Re: [atompie/tracardi] Events dint load after connecting to unomi (#9)


@lokeshgrootan<https://github.com/lokeshgrootan> Hi This can be a problem with your time zone. What time zone are you in? Could you give it a test and set a wide time range and see what the difference of the actual time the event was triggered and the time you see it in Tracardi.

We have been working on timezone issue recently but t can still exist.

**Comment by atompie** [comment]
Perfect :)
