### ISSUE TITLE
Connect Tracardi to OpenSearch

### ISSUE THREAD

**Issue by atompie** [atompie/tracardi#93]
# Description of the task

We want to test if we can connect Tracardi to OpenSearch. Tracardi uses Elasticsearch as its database. OpenSearch is a clone of Elastica and should work the same. Therefore, the task is to install opensearch from e.g. dockerahub

* https://hub.docker.com/r/opensearchproject/opensearch

and to check that all Tracardi's functions are working properly. From the preliminary findings, everything should work fine. The biggest problems may be with the search engine because we use elastic SQL which may be at a different URL in OpenSearch. There is a way to change this endpoint (see below)

# Tracardi installation

Information on installing Tracardi can be found here:

* https://github.com/atompie/tracardi-api/blob/0.6.0-dev/manual/en/docs/installation/index.md

You may need to connect a different endpoint in Tracardi to SQL. Below is a link with information on how to do it.

* https://github.com/atompie/tracardi-api/blob/0.6.0-dev/manual/en/docs/installation/elasticsearch/sql_translation_configuration.md

If you have any questions, please feel free to ask them below in the comments.

**Comment by suhail34** [comment]
Hey @atompie i would like to contribute this issue can u suggest some ways to get started

**Comment by atompie** [comment]
@suhail34 Just install Tracardi from docker (follow: https://github.com/atompie/tracardi-api/blob/0.6.0-dev/manual/en/docs/installation/index.md)

For this task you do not need to code.

And then install OpenSearch from docker and try to run it together. This is just switching configurations.

**Comment by atompie** [comment]
@suhail34 you can look at our youtube channel to understand what the project is about: https://www.youtube.com/channel/UC0atjYqW43MdqNiSJBvN__Q

**Comment by suhail34** [comment]
Thanks for the help @atompie .It will be really helpfull

**Comment by suhail34** [comment]
Hey @atompie in which file the changes need to be made. I am in search of it 😅

**Comment by suhail34** [comment]
Hey @atompie do i need to make this changes in docker-compose.yaml

**Comment by atompie** [comment]
No just configure connection to opensearch in env variables.

**Comment by atompie** [comment]
Checked and fixed in 0.6.0
